version: '3.4'

services:
 catalogdb: 
  image: postgres

volumes:
  postgres_catalog:

  #catalog_api:
  #  image: ${DOCKER_REGISTRY-}catalogapi
  #  build:
  #    context: .
  #    dockerfile: Services/Catalog/Catalog_API/Dockerfile
